"""add_user_table

Revision ID: 0e54a770ef36
Revises: f8d3a50cd2f1
Create Date: 2026-01-14 09:42:52.710698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0e54a770ef36'
down_revision: Union[str, Sequence[str], None] = 'f8d3a50cd2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
    CREATE TYPE userrole AS ENUM ('ADMIN', 'COACH', 'ANALYST', 'PLAYER');
  END IF;
END$$;
""")
    op.execute("""
CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  hashed_password VARCHAR(255) NOT NULL,
  role userrole NOT NULL,
  is_active BOOLEAN NOT NULL,
  full_name VARCHAR(255),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
""")
op.execute("""
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'ix_user_email' AND n.nspname = 'public'
  ) THEN
    CREATE UNIQUE INDEX ix_user_email ON "user" (email);
  END IF;
END
$$;
""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
    DROP TYPE userrole;
  END IF;
END$$;
""")
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
