"""add_injury_coordinates

Revision ID: 18d312554f1c
Revises: 14a3aca86c75
Create Date: 2026-02-13 18:25:10.748139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '18d312554f1c'
down_revision: Union[str, Sequence[str], None] = '14a3aca86c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('injury', sa.Column('coord_x', sa.Float(), nullable=True))
    op.add_column('injury', sa.Column('coord_y', sa.Float(), nullable=True))
    op.alter_column('injury', 'body_part',
               existing_type=postgresql.ENUM('CERVICALES', 'EPAULES', 'COUDES', 'POIGNETS', 'ADDUCTEURS', 'CUISSES', 'GENOUX', 'CHEVILLES', name='bodypart'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('injury', 'body_part',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=postgresql.ENUM('CERVICALES', 'EPAULES', 'COUDES', 'POIGNETS', 'ADDUCTEURS', 'CUISSES', 'GENOUX', 'CHEVILLES', name='bodypart'),
               nullable=False)
    op.drop_column('injury', 'coord_y')
    op.drop_column('injury', 'coord_x')
    # ### end Alembic commands ###
