"""Add position field to User

Revision ID: 32f0864c8ac0
Revises: 2c3d4e5f6a7b
Create Date: 2026-02-13 14:06:32.044613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32f0864c8ac0'
down_revision: Union[str, Sequence[str], None] = '2c3d4e5f6a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_constraint('catapultsession_user_id_fkey', 'catapultsession', type_='foreignkey')
    op.create_foreign_key(None, 'catapultsession', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.drop_constraint('fk_user_team', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_team', 'user', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'position')
    op.drop_constraint(None, 'catapultsession', type_='foreignkey')
    op.create_foreign_key('catapultsession_user_id_fkey', 'catapultsession', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='player_team_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='player_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_pkey')
    )
    # ### end Alembic commands ###
