"""add selected_catapult_session_id to user

Revision ID: cc1ce2b2f1bf
Revises: b2c3d4e5f6a7
Create Date: 2026-04-09 09:31:57.199366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1ce2b2f1bf'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('selected_catapult_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'catapultsession', ['selected_catapult_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'selected_catapult_session_id')
    # ### end Alembic commands ###
