"""Initial schema

Revision ID: f8d3a50cd2f1
Revises: 
Create Date: 2026-01-11 11:18:02.038022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d3a50cd2f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('academy_country_id_fkey'), 'academy', type_='foreignkey')
    op.create_foreign_key(None, 'academy', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('player_equipe_id_fkey'), 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('team_academy_id_fkey'), 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'academy', ['academy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key(op.f('team_academy_id_fkey'), 'team', 'academy', ['academy_id'], ['id'])
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(op.f('player_equipe_id_fkey'), 'player', 'team', ['team_id'], ['id'])
    op.drop_constraint(None, 'academy', type_='foreignkey')
    op.create_foreign_key(op.f('academy_country_id_fkey'), 'academy', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###
