"""Add user profile fields

Revision ID: tmp_add_user_fields_1771506972
Revises: 1771231664_add_user_photo_url
Create Date: 2026-02-19 13:16:13.257939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'tmp_add_user_fields_1771506972'
down_revision: Union[str, Sequence[str], None] = '1771231664_add_user_photo_url'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('adress', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('strong_foot', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user', sa.Column('emergency_contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('user', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'photo_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('user', 'emergency_contact')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'strong_foot')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'height')
    op.drop_column('user', 'adress')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
